import { Nunito_Sans } from 'next/font/google'
import "./globals.css";



const nunitoSans  = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-nunito-sans',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.variable} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
